# Generated by Django 2.0.3 on 2018-03-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
